using UnityEngine;

// Daily quests: 3 small goals per day, auto-rewarded. Regenerated by EndDay.
public static class QuestSystem
{
    public class Quest
    {
        public int type;      // 0 catch fish, 1 sell fish, 2 dump trash
        public int target;
        public int progress;
        public int reward;
        public bool done;

        public string Line()
        {
            string what = type == 0 ? "Balik yakala" : type == 1 ? "Balik sat" : "Cop at";
            string state = done ? "TAMAM!" : progress + "/" + target;
            return what + " (" + state + ")  +$" + B.Money(reward);
        }
    }

    public static Quest[] quests = new Quest[0];

    public static void Clear() { quests = new Quest[0]; }

    public static void GenerateDaily()
    {
        if (Game.gm == null) { quests = new Quest[0]; return; }
        int lvl = Game.gm.Level;
        quests = new Quest[3];
        quests[0] = Make(0, 5 + lvl, 20 + lvl * 12);
        quests[1] = Make(1, 4 + lvl, 25 + lvl * 15);
        quests[2] = Make(2, 3, 30 + lvl * 8);
    }

    static Quest Make(int type, int target, int reward)
    {
        Quest q = new Quest();
        q.type = type;
        q.target = Mathf.Max(1, target + Random.Range(-1, 2));
        q.reward = reward;
        return q;
    }

    static void Bump(int type, int n)
    {
        if (Game.gm == null) return;
        for (int i = 0; i < quests.Length; i++)
        {
            Quest q = quests[i];
            if (q == null || q.done || q.type != type) continue;
            q.progress += n;
            if (q.progress >= q.target)
            {
                q.done = true;
                Game.gm.AddMoney(q.reward);
                Sfx.Play(Snd.Collect, 0.8f);
                if (Game.ui != null)
                {
                    Game.ui.Toast("GOREV TAMAM! +$" + B.Money(q.reward));
                    Game.ui.MoneyPunch();
                }
            }
        }
    }

    public static void OnCatch() { Bump(0, 1); }
    public static void OnSell() { Bump(1, 1); }
    public static void OnTrash(int n) { Bump(2, n); }
}
